### ISSUE TITLE
Include license file in repo and crate

### ISSUE THREAD

**Issue by ankane** [jorgecarleitao/json-deserializer#15]
Hi, thanks for this crate (currently using it as part of [Polars](https://github.com/pola-rs/polars))! It looks like `Cargo.toml` specifies the license as `Apache-2.0`, but it'd be nice to include a license file in the repo (which Cargo should automatically include in the published crate if present).

I also noticed you're the owner of the `arrow-format` crate - would be nice to do the same there.

**Comment by jorgecarleitao** [comment]
Thanks! Fixed and released to crates under v0.4.3 :)

**Comment by ankane** [comment]
Wow, that was super fast - thanks a ton (for both)!
